<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Anchor CMS</title>
	<style>
	a {
		color: #497bad;
		text-decoration:none;
	}
	a:hover {
		text-decoration: underline !important;
	}
	td.promocell p {
		color:#596270;
		font-size:24px;
		line-height:26px;
		font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;
		margin-top:0;
		margin-bottom:0;
		padding-top:0;
		padding-bottom:14px;
		font-weight:normal;
	}
	td.contentblock h4 {
		color:#596270 !important;
		font-size:16px;
		line-height:24px;
		font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;
		margin-top:0;
		margin-bottom:10px;
		padding-top:0;
		padding-bottom:0;
		font-weight:normal;
	}
	td.contentblock h4 a {
		color:#596270;
		text-decoration:none;
	}
	td.contentblock p,
	td.contentblock em {
	  	color:#596270;
		font-size:13px;
		line-height:19px;
		font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;
		margin-top:0;
		margin-bottom:12px;
		padding-top:0;
		padding-bottom:0;
		font-weight:normal;
	}
	td.contentblock p a {
	  	color:#3ca7dd;
		text-decoration:none;
	}
	@media only screen and (max-device-width: 480px) {
	     div[class="header"] {
	          font-size: 16px !important;
	     }
	     table[class="table"], td[class="cell"] {
	          width: 320px !important;
	     }
		 td[class="footershow"] {
	          width: 300px !important;
	     }
		 table[class="hide"], img[class="hide"], td[class="hide"] {
	          display: none !important;
	     }
	     img[class="divider"] {
		      height: 1px !important;
		 }
	     img[id="screenshot"] {
	          width: 325px !important;
	          height: 127px !important;
	     }
		h4[class="secondary"] {
			line-height: 22px !important;
			margin-bottom: 15px !important;
			font-size: 18px !important;
		}
	}
	</style>
</head>
<body bgcolor="#e4e7ec" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" style="-webkit-font-smoothing: antialiased;width:100% !important;background:#e4e7ec;-webkit-text-size-adjust:none;">

	<table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#e4e7ec">
		<tr>
			<td bgcolor="#e4e7ec" width="100%">
			<table width="600" cellpadding="0" cellspacing="0" border="0" align="center" class="table">
				<tr>
					<td width="600" class="cell">
						<table width="600" cellpadding="0" cellspacing="0" border="0" class="table">
							<tr>
								<td width="250" bgcolor="#e4e7ec" class="logocell">
									<img border="0" src="images/spacer.gif" width="1" height="25" class="hide"><br class="hide">
									<img src="<?php echo asset('assets/img/logo.png'); ?>" width="24" height="22" alt="Anchor" style="-ms-interpolation-mode:bicubic;"><br>
									<img border="0" src="images/spacer.gif" width="1" height="25" class="hide"><br class="hide">
								</td>
								<td align="right" width="350" class="hide" style="color:#707b8c;font-size:12px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;" valign="middle" bgcolor="#e4e7ec">
									<span><span class="hide">Make blogging beautiful — </span>Anchor CMS</span>
								</td>
							</tr>
						</table>
						<img border="0" src="<?php echo asset('assets/img/hero.png'); ?>" label="Hero image" editable="true" width="600" height="253" id="screenshot">
						<!--
						<table width="600" cellpadding="30" cellspacing="0" border="0" class="promotable">
							<tr>
								<td bgcolor="#ffffff" width="600" class="promocell">
									<p>Thank you</p>
								</td>
							</tr>
						</table>
						-->
						<table width="100%" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td width="100%" bgcolor="#ffffff">
									<table width="100%" cellpadding="30" cellspacing="0" border="0">
										<tr>
											<td bgcolor="#ffffff" class="contentblock">
												<h4 class="secondary"><strong>Thank you for contributing to Anchor CMS</strong></h4>
												<p>We really appreciate your donation, which we will use to maintain hosting of our main sites.</p><p>Additionally, it will help future services required to make Anchor the best content management system we can.</p>
												<br>
												<em>Anchor CMS team</em>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
						<img border="0" src="images/spacer.gif" width="1" height="25" class="divider"><br>
					</td>
				</tr>
			</table>
			<img border="0" src="images/spacer.gif" width="1" height="25"><br>
			<table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#f8f9fa">
				<tr>
					<td>
						<img border="0" src="images/spacer.gif" width="1" height="30"><br>
						<table width="600" cellpadding="0" cellspacing="0" border="0" align="center" class="table">
							<tr>
								<td width="600" nowrap bgcolor="#f8f9fa" class="cell">
									<table width="600" cellpadding="0" cellspacing="0" border="0" class="table">
										<tr>
											<td width="380" valign="top" class="footershow">
												<p style="color:#c9c9c9;font-size:12px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">&nbsp;</p>
											</td>
											<td align="right" width="220" style="color:#a6a6a6;font-size:12px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;" valign="middle" class="hide">
												<table cellpadding="0" cellspacing="0" border="0">
													<tr>
														<td><a href="http://anchorcms.com/">Anchor CMS</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://twitter.com/anchorcms">Twitter</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://github.com/anchorcms">GitHub</a></td>
													</tr>
												</table>
											</td>
										</tr>
									</table>

								</td>
							</tr>
				   		</table>
						<img border="0" src="images/spacer.gif" width="1" height="25"><br>
					</td>
				</tr>
			</table>
			</td>
		</tr>
	</table>
</body>
</html>
